general {
    lock_cmd = hyprlock || hyprlock
}

listener {
    timeout = 300                           
    on-timeout = brightnessctl -s set 10         
    on-resume = brightnessctl -r                 
}

listener {
    timeout = 350  
    on-timeout = notify-send "Sto per bloccarmi"  
}

listener {
    timeout = 400
    on-timeout = loginctl lock-session
}
